defaults:
  run:
    shell: bash
jobs:
  build:
    name: Java ${{ matrix.Java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Test with Maven
      run: mvn test -B -f ./aliyun-java-sdk-core/pom.xml
    - continue-on-error: true
      name: Post test coverage
      run: bash <(curl -s https://codecov.io/bash) -cF java
    strategy:
      matrix:
        java:
        - 8
        - 11
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
